function Hd = notch60hzv1
%NOTCH60HZV1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 08-Jan-2024 19:34:03

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 192;  % Sampling Frequency

Fnotch = 60;  % Notch Frequency
BW     = 10;  % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
